ktor:
    application:
        modules:
            - com.github.matheusfbosa.order.ApplicationKt.module
    deployment:
        port: 8080

kafka:
    bootstrap-servers: "localhost:29092"
    topic: orders
