ktor:
    application:
        modules:
            - com.github.matheusfbosa.shipment.ApplicationKt.module
    deployment:
        port: 8081

kafka:
    bootstrap-servers: "localhost:29092"
    topic: orders
